# PATH 无 java，显式指向 Android Studio 自带 JBR

org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -Dkotlin.daemon.jvmargs=-Xmx2g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.incremental=true
ksp.incremental=true
android.cacheFixGradlePlugin=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
