/**
 * Muses 业务图标语义表。
 *
 * 所有导出均为 @lucide/vue 组件，页面以 <component :is> 直接渲染。
 */
export {
  Play as play,
  Play as playOutline,
  Pause as pause,
  SkipBack as playSkipBack,
  SkipForward as playSkipForward,
  Shuffle as shuffle,
  ListOrdered as listOutline,
  ListMusic as list,
  Library as library,
  Repeat as repeatOutline,
  Repeat1 as repeat,
  Music as musicalNotes,
  Music as musicalNotesOutline,
  Disc3 as albums,
  MicVocal as person,
  Folder as radio,
  Settings as settings,
  House as home,
  Clock as clockOutline,
  History as historyOutline,
  Search as searchOutline,
  Plus as add,
  Plus as addOutline,
  X as close,
  Trash2 as trash,
  ChevronLeft as chevronBack,
  Languages as languageOutline,
  Languages as languageOffOutline,
  Locate as locateOutline,
  Crosshair as crosshair,
  EllipsisVertical as ellipsisVertical,
  Menu as menu,
  CircleMinus as removeCircleOutline,
  ArrowUpDown as arrowUpDown,
  ListChecks as listChecks,
  CheckCheck as checkCheck,
  Volume2 as volume2,
  Sun as sun,
  Moon as moon,
  Monitor as monitor,
} from '@lucide/vue'
